nouns=['oxford', 'sunday', 'thursday', 'wednesday', 'freddie gray', 'tuesday', 'bill haslam', 'lgbt', 'manson', 'dna', 'veronica conrado',
 'reet jurvetson', 'congress', 'yorkville', 'house speaker', 'federal district', 'democratic', 'democrats', 'republican', 'gop', 'paris',
 'montreal', 'milwaukee', 'illinois', 'tennessee', 'belgium', 'france', 'volvo', 'london','los angeles', 'white house', 'buzzfeed', 
 'united states', 'albama', 'new york times', 'fox news', 'university of virginia', 'chipotle', 'san francisco', 'latino', 'google', 'uber',
  'lyft', 'ford', 'muslim', 'ceo', 'geri taylor', 'alzheimers', 'speaker of the house', 'church of england', 'god', 'britain', 'grindr', 
  'iphone', 'mexico', 'modern love', 'game of thrones', 'veep', 'arya stark', 'matthew', 'scott cross', 'barefoot bandit', 'madison avenue',
   'middle eastern', 'east', 'israel', 'apple','iphone', 'justice dept', 'olympic', 'greece', 'temple hera', 'supreme court', 'iran', 'seol',
    'korea', 'lackland', 'air force base', 'antonio', 'villanova', 'north carolina', 'mens basketball championship', 'greyhound',
     'state police', 'washington', 'twitter', 'marijuana', 'nsa', 'pluto', 'saudi arabia', 'africa', 'comcast', 'nintendo', 'mitsubishi', 
     'dreamworks', 'lenovo', 'xiaomi', 'facebook', 'cupertino', 'nyc', 'australia', 'nasa', 'hbo', 'jungle book', 'john wayne day', 
     'jurassic park', 'lucifer', 'becky', 'english', 'brother nelson', 'captain america', 'american', 'celtics', 'brad stevens', 
     'gary washburn', 'syrian', 'puerto rico', 'germany', 'cleaveland', 'baghdad', 'manhattan', 'obamacare', 'china', 'amazon', 
     'senator', 'burka', 'democrat', 'frank vandersloot', 'clara smith', 'christopher ilitich', 'dan gilbert', 'kid rock', 
     'himalayas', 'bank brian moynihan', 'warren buffett', 'wall street', 'salesforce', 'marc benioff', 'keith rabois', 'valeant', 
     'ghostbusters', 'paul veig', 'alexis stenfors', 'jim brulte', 'california', 'republican party']


people=['chris wallace', 'trump', 'hillary clinton', 'bernie sanders', 'dennis hastert', 'thomas durkin', 'ted cruz', 'jack dorsey',
 'dennis hastert', 'donald trump', 'maisie williams', 'obama', 'clinton', 'trump', 'snowden', 'kendall jenner', 'drake', 'zuckerberg',
  'beyonce', 'joe bidden', 'ricky gervais', 'romeo', 'juliet', 'reagan', 'kim jong un', 'hosiers', 'barack obama', 'mayor emanuel', 'kim',
   'kanye', 'conn. governor', 'dannel malloy', 'david price', 'patriots', 'brissett', 'ben volin', 'michael bloomberg', 'elizabeth warren',
    'dj khaled', 'paton oswalt', 'cher', 'john kasich', 'justin trudeau', 'malcolm turnbull', 'warren buffet', 'bill ackman',
     'floyd mayweather', 'morgan stanley', 'jessica alba', 'nick offerman', 'hulk hogan', 'prince' ]



emotive= ['proud', 'integral', 'challenge', 'bans', 'importance', 'discuss', 'shed', 'defeated', 'expected', 'survive', 'shooting',
 'unrest', 'funeral', 'refuse', 'enact', 'reject', 'identified', 'stabbed', 'infamous', 'confirm', 'passionately', 'defended', 'deserved',
  'molester', 'died', 'fatally', 'sweeping', 'presumptive', 'extradited', 'clinch', 'justifying', 'abandon', 'influence', 'accelerate',
   'adoption', 'lashed out', 'modestly', 'struggling', 'experience', 'joy', 'discover', 'wisps', 'beginning', 'frustration', 'learn',
    'learned', 'control', 'stunning', 'molestation', 'debate', 'honesty', 'openness', 'truth', 'gay', 'pay', 'expensive', 'deal', 'swipe',
     'want', 'wanted', 'talk', 'self-image', 'putting', 'thriving', 'retiring', 'prepared', 'date', 'tremendous', 'impatient', 'fans',
      'inviting', 'invite', 'invited', 'seek', 'expect', 'romance', 'yell', 'stop', 'interrupting', 'accident', 'suffocate', 'surrogate',
       'elected', 'found', 'dead', 'idiots', 'trusted', 'remain', 'silent', 'against', 'core', 'beliefs', 'sure', 'killing', 'needs',
        'drunken', 'unprecedented', 'overly', 'celebratory', 'heroic', 'gender', 'prevent', 'addict', 'looming, catastrophe', 'legalize',
         'harder', 'spying', 'scary', 'effect', 'devastated', 'major', 'announcement', 'fit', 'rage', 'jerk', 'crisis', 'accused',
          'promoting', 'cheating', 'admitted', 'pleads', 'soar', 'cease', 'dazzling', 'holy schnikes', 'eradicate', 'struggle', 'radically',
           'killed', 'lawsuit', 'discrimination', 'confess', 'botching', 'betting', 'lying', 'outperforming', 'sorry', 'clumsy', 'kill',
            'miracle', 'bizarre', 'felt', 'crossing', 'presidential', 'easiest', 'ever', 'live', 'country', 'people', 'diversity', 'think',
             'protest', 'protestor', 'bigot', 'different', 'opinion', 'accept', 'good', 'punish', 'should not', 'deciding', 'family',
              'forced', 'be', 'spending time', 'racism', 'sexism', 'bitch', 'absolutely', 'moral', 'obligation', 'gather', 'thoughts',
               'earned', 'right', 'fight', 'teach', 'problem', 'fluent', 'defining', 'moment', 'globe', 'consequences', 'treated', 'treat',
                'irony', 'punches', 'thrown', 'towering', 'grand', 'compromise', 'boyfriend', 'dereliction', 'duty', 'explanation',
                 'unhealthy', 'obsession', 'revenge', 'seriousness', 'home', 'incredible', 'act', 'courage', 'decency', 'terrible',
                  'tragedy', 'witness', 'now', 'firsthand', 'suffer', 'young', 'die', 'great', 'safety', 'record', 'relationship', 'best',
                   'twisted', 'loyalty', 'unapologetic', 'hellish', 'years', 'addiction', 'opportunity', 'blew', 'faithful', 'job',
                    'convicted', 'presence', 'criminal', 'detective', 'force', 'marked', 'club', 'belong', 'christened', 'officially',
                     'trigger', 'warnings', 'significant', 'anti-muslim', 'manifesto', 'touching', 'spine-tingling', 'rival', 'confronts',
                      'anti-gay', 'dooming', 'brutal', 'beating', 'despicable', 'rebukes', 'abused', 'tasteless', 'guilty', 'recalls',
                       'modernized', 'wildest', 'upping', 'ante', 'outstripping', 'shakeup', 'standoff', 'emerging', 'powerful',
                        'controversial', 'historic', 'regret', 'famed', 'averted', 'disturbing', 'ferocious', 'investigated', 
                        'cringeworthy', 'worst', 'inspires', 'spookily', 'suing', 'raging', 'destroyed', 'exposing', 'hack', 
                        'explosive', 'awkward', 'goofed', 'worse', 'fell', 'grace', 'god', 'scheme', 'trying', 'paint', 'vision', 'can', 
                        'done', 'member', 'greatest', 'men', 'pleasure', 'friends', 'unites', 'divides', 'much', 'more', 'whether', 'new', 
                        'clean', 'matters', 'write', 'sharpening', 'online', 'attack', 'content', 'raped', 'complain', 'really', 'wrong', 
                        'firmly', 'brand', 'established', 'outsider', 'candidates', 'end literally', 'only', 'choices', 'acceptable', 
                        'traditional', 'exactly', 'activism', 'beyond', 'issues', 'salesmanship', 'abilities', 'investment', 
                        'advocate', 'raising', 'inflated', 'deserve', 'pigeonholed', 'mean', 'happy', 'definitely', 'scapegoat' ]